In [564]:
import pandas as pd 
import numpy as np
from sklearn import linear_model
import joblib
from sklearn.model_selection import train_test_split

In [565]:
df = pd.read_csv('./data/CarPrice_Assignment.csv')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

## Cleaning the data set

In [566]:
columns =[]
for i in df:
    columns.append(i)
columns

['car_ID',
 'symboling',
 'CarName',
 'fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginetype',
 'cylindernumber',
 'enginesize',
 'fuelsystem',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',
 'price']

In [567]:
df_x = df.drop('price',axis="columns")
df_x

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,six,145,idi,3.01,3.40,23.0,106,4800,26,27
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25

In [568]:
dummy  = pd.get_dummies(df_x[['CarName','enginelocation','fueltype','aspiration','carbody','drivewheel','fuelsystem','enginetype']],drop_first = True)
dummy

,CarName_alfa-romero Quadrifoglio,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi 4000,CarName_audi 5000,CarName_audi 5000s (diesel),CarName_audi fox,CarName_bmw 320i,...,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor
0,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
201,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
202,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
203,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
204,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [569]:
df_x = df_x.drop(['CarName','enginelocation','fueltype','aspiration','carbody','drivewheel','fuelsystem','enginetype'],axis="columns")
df_x

,car_ID,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1,3,two,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111,5000,21,27
1,2,3,two,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111,5000,21,27
2,3,1,two,94.5,171.2,65.5,52.4,2823,six,152,2.68,3.47,9.0,154,5000,19,26
3,4,2,four,99.8,176.6,66.2,54.3,2337,four,109,3.19,3.40,10.0,102,5500,24,30
4,5,2,four,99.4,176.6,66.4,54.3,2824,five,136,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,four,109.1,188.8,68.9,55.5,2952,four,141,3.78,3.15,9.5,114,5400,23,28
201,202,-1,four,109.1,188.8,68.8,55.5,3049,four,141,3.78,3.15,8.7,160,5300,19,25
202,203,-1,four,109.1,188.8,68.9,55.5,3012,six,173,3.58,2.87,8.8,134,5500,18,23
203,204,-1,four,109.1,188.8,68.9,55.5,3217,six,145,3.01,3.40,23.0,106,4800,26,27
204,205,-1,four,109.1,188.8,68.9,55.5,3062,four,141,3.78,3.15,9.5,114,5400,19,25

In [570]:
final_categorical = pd.concat([df_x,dummy],axis="columns")
final_categorical

,car_ID,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,...,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor
0,1,3,two,88.6,168.8,64.1,48.8,2548,four,130,...,0,1,0,0,0,0,0,0,0,0
1,2,3,two,88.6,168.8,64.1,48.8,2548,four,130,...,0,1,0,0,0,0,0,0,0,0
2,3,1,two,94.5,171.2,65.5,52.4,2823,six,152,...,0,1,0,0,0,0,0,0,1,0
3,4,2,four,99.8,176.6,66.2,54.3,2337,four,109,...,0,1,0,0,0,0,1,0,0,0
4,5,2,four,99.4,176.6,66.4,54.3,2824,five,136,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,four,109.1,188.8,68.9,55.5,2952,four,141,...,0,1,0,0,0,0,1,0,0,0
201,202,-1,four,109.1,188.8,68.8,55.5,3049,four,141,...,0,1,0,0,0,0,1,0,0,0
202,203,-1,four,109.1,188.8,68.9,55.5,3012,six,173,...,0,1,0,0,0,0,0,0,1,0
203,204,-1,four,109.1,188.8,68.9,55.5,3217,six,145,...,0,0,0,0,0,0,1,0,0,0
204,205,-1,four,109.1,188.8,68.9,55.5,3062,four,141,...,0,1,0,0,0,0,1,0,0,0

In [571]:
def is_nan(x):
    return x!=x

In [572]:
number  = ['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve']

def w2n_doornumber():
    count=0
    get_num=0
    for i in final_categorical.doornumber:
        j=0
        if is_nan(i):
            count= count+1
            continue
        for j in range(len(number)):
            if i==number[j]:
                get_num = j
                break
        final_categorical.doornumber[count]=get_num
        count= count+1
def w2n_cylindernumber():
    count=0
    get_num=0
    for i in final_categorical.cylindernumber:
        j=0
        if is_nan(i):
            count= count+1
            continue
        for j in range(len(number)):
            if i==number[j]:
                get_num = j
                break
        final_categorical.cylindernumber[count]=get_num
        count= count+1 
w2n_cylindernumber()
w2n_doornumber()

C:\Users\Shadin\AppData\Local\Temp/ipykernel_4208/3683234636.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_categorical.cylindernumber[count]=get_num
C:\Users\Shadin\AppData\Local\Temp/ipykernel_4208/3683234636.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_categorical.doornumber[count]=get_num

In [573]:
final_categorical

,car_ID,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,...,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor
0,1,3,2,88.6,168.8,64.1,48.8,2548,4,130,...,0,1,0,0,0,0,0,0,0,0
1,2,3,2,88.6,168.8,64.1,48.8,2548,4,130,...,0,1,0,0,0,0,0,0,0,0
2,3,1,2,94.5,171.2,65.5,52.4,2823,6,152,...,0,1,0,0,0,0,0,0,1,0
3,4,2,4,99.8,176.6,66.2,54.3,2337,4,109,...,0,1,0,0,0,0,1,0,0,0
4,5,2,4,99.4,176.6,66.4,54.3,2824,5,136,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,4,109.1,188.8,68.9,55.5,2952,4,141,...,0,1,0,0,0,0,1,0,0,0
201,202,-1,4,109.1,188.8,68.8,55.5,3049,4,141,...,0,1,0,0,0,0,1,0,0,0
202,203,-1,4,109.1,188.8,68.9,55.5,3012,6,173,...,0,1,0,0,0,0,0,0,1,0
203,204,-1,4,109.1,188.8,68.9,55.5,3217,6,145,...,0,0,0,0,0,0,1,0,0,0
204,205,-1,4,109.1,188.8,68.9,55.5,3062,4,141,...,0,1,0,0,0,0,1,0,0,0

In [574]:
def clean():
    count=0
    
    for i in final_categorical.symboling:  
        if i<0:
            final_categorical.symboling[count]=0
        count=count+1
clean()
final_categorical

C:\Users\Shadin\AppData\Local\Temp/ipykernel_4208/4035521723.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_categorical.symboling[count]=0

,car_ID,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,...,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor
0,1,3,2,88.6,168.8,64.1,48.8,2548,4,130,...,0,1,0,0,0,0,0,0,0,0
1,2,3,2,88.6,168.8,64.1,48.8,2548,4,130,...,0,1,0,0,0,0,0,0,0,0
2,3,1,2,94.5,171.2,65.5,52.4,2823,6,152,...,0,1,0,0,0,0,0,0,1,0
3,4,2,4,99.8,176.6,66.2,54.3,2337,4,109,...,0,1,0,0,0,0,1,0,0,0
4,5,2,4,99.4,176.6,66.4,54.3,2824,5,136,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,0,4,109.1,188.8,68.9,55.5,2952,4,141,...,0,1,0,0,0,0,1,0,0,0
201,202,0,4,109.1,188.8,68.8,55.5,3049,4,141,...,0,1,0,0,0,0,1,0,0,0
202,203,0,4,109.1,188.8,68.9,55.5,3012,6,173,...,0,1,0,0,0,0,0,0,1,0
203,204,0,4,109.1,188.8,68.9,55.5,3217,6,145,...,0,0,0,0,0,0,1,0,0,0
204,205,0,4,109.1,188.8,68.9,55.5,3062,4,141,...,0,1,0,0,0,0,1,0,0,0

## The dataset has been cleaned

# Now to train the model

## first we need to split the dataset

In [575]:
y=df['price']
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [582]:
x_train,x_test,y_train,y_test = train_test_split(final_categorical,y,test_size=0.2)

In [583]:
car_model =  linear_model.LinearRegression()

In [584]:
car_model.fit(x_train,y_train)

LinearRegression()

In [585]:
car_model.score(x_test,y_test)

-0.7922971353805177